default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>

development:
  <<: *default
  username: postgres
  password: postgres
  database: chatwoot_dev

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'chatwoot_test') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>

production:
  <<: *default
  username: postgres
  password: postgres
  database: chatwoot_prod
