default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', '5432') %>

development:
  <<: *default
  username: postgres
  password: postgres
  database: chatwoot_dev

test:
  <<: *default
  username: postgres
  password: postgres
  database: chatwoot_test

production:
  <<: *default
  username: postgres
  password: postgres
  database: chatwoot_prod
